melding = input('Hva skal kua si? ')

print(' ____________________')
print('< ' , melding , ' >')
print(' --------------------')
print('     \   ^__^')
print('      \  (oo)\_______')
print('         (__)\       )')
print('             ||----W |')
print('             ||     ||')